# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kalio\.spyder-py3\Program\PYQT\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setStyleSheet("\"background-color: cyan;\"")
        self.frame2 = QtWidgets.QFrame(Form)
        self.frame2.setEnabled(True)
        self.frame2.setGeometry(QtCore.QRect(120, 40, 350, 310))
        self.frame2.setStyleSheet("")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setLineWidth(100)
        self.frame2.setMidLineWidth(0)
        self.frame2.setObjectName("frame2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(120, 0, 261, 51))
        self.frame.setMouseTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(100)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 158, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.yylifo_pushButton = QtWidgets.QPushButton(self.widget)
        self.yylifo_pushButton.setObjectName("yylifo_pushButton")
        self.gridLayout.addWidget(self.yylifo_pushButton, 0, 1, 1, 1)
        self.frame3 = QtWidgets.QFrame(Form)
        self.frame3.setGeometry(QtCore.QRect(10, 60, 111, 311))
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.listWidget = QtWidgets.QListWidget(self.frame3)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 91, 281))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Config"))
        self.yylifo_pushButton.setText(_translate("Form", "yyinfo"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "CONFIG"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "YYINFO"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
